"""rename nikname to nickname

Revision ID: 60424d9f0b37
Revises: 89d803368872
Create Date: 2026-06-08 14:06:16.386828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60424d9f0b37'
down_revision: Union[str, Sequence[str], None] = '89d803368872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('user_nikname_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.drop_column('user', 'nikname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nikname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_nikname_key'), 'user', ['nikname'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
