"""rename task_description

Revision ID: af43ec6b5a4f
Revises: 098b2edb033a
Create Date: 2026-06-15 08:18:01.372453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af43ec6b5a4f'
down_revision: Union[str, Sequence[str], None] = '098b2edb033a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('task_description', sa.Text(), nullable=True))
    op.drop_column('cards', 'tast_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('tast_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'task_description')
    # ### end Alembic commands ###
